apiVersion: v1
kind: Namespace
metadata:
  name: camelpd-dev
  labels:
    name: camelpd-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secret # changed name
  namespace: camelpd-dev
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: password
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJrYnN0YWdpbmcuYXp1cmVjci5pbyI6eyJ1c2VybmFtZSI6ImRkYTdjZjA0LTllYWYtNDgzNS04ZTdmLWFlNjk5NzU1NzYxOSIsInBhc3N3b3JkIjoiMVppbi4zZzllRndUWEdxS0xoU2UzdC1CRFlvQnkuX2VFdiIsImF1dGgiOiJaR1JoTjJObU1EUXRPV1ZoWmkwME9ETTFMVGhsTjJZdFlXVTJPVGszTlRVM05qRTVPakZhYVc0dU0yYzVaVVozVkZoSGNVdE1hRk5sTTNRdFFrUlpiMEo1TGw5bFJYWT0ifX19
kind: Secret
metadata:
  creationTimestamp: "2021-10-29T21:14:26Z"
  name: acr-secret
  namespace: camelpd-dev
  resourceVersion: "51539"
  uid: 70a89983-1897-4644-a7cb-fd54fe5229a4
type: kubernetes.io/dockerconfigjson
