apiVersion: v1
kind: Namespace
metadata:
  name: camelpd-dev
  labels:
    name: camelpd-dev
---
apiVersion: v1
kind: Secret
metadata:
  name: mysqldb-secret # changed name
  namespace: camelpd-dev
type: kubernetes.io/basic-auth
stringData:
  username: root
  password: password
