apiVersion: v1
kind: Service
metadata:
  name: camelpd-api-dpl-svc
  namespace: camelpd-dev
  labels:
    app: camelpd-api-deployment
spec:
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 32222
    protocol: TCP
  type: LoadBalancer
  selector:
    app: camelpd-api-deployment