apiVersion: v1
kind: Service
metadata:
  name: camelpd-api-dpl-svc
  namespace: camelpd-dev
  labels:
    app: camelpd-api-deployment
  annotations:
    konghq.com/plugins: name-restrict,camelpd-api-jwt,custom-json-request-validation # for kong plugins
spec:
  ports:
  - port: 8090
    targetPort: 8090
    nodePort: 32222
    protocol: TCP
  type: NodePort
  selector:
    app: camelpd-api-deployment